api_platform:
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 30

        pagination_client_enabled: true
        pagination_client_items_per_page: true
    collection:
            pagination:
                enabled_parameter_name: pagination
                items_per_page_parameter_name: itemsPerPage
                page_parameter_name: page
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    use_symfony_listeners: false
    formats:
        jsonld: ['application/ld+json', 'application/merge-patch+json']
        multipart: ['multipart/form-data']
