api_platform:
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    use_symfony_listeners: false
    formats:
      jsonld: ['application/ld+json']
      multipart: ['multipart/form-data']
