api_platform:
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    use_symfony_listeners: false
    formats:
         jsonld: ['application/ld+json']
         multipart: ['multipart/form-data']
    # patch_formats:
    #     jsonld: ['application/merge-patch+json']
    # error_formats:
    #     jsonproblem: ['application/problem+json']
    #     jsonld: ['application/ld+json'] 
    #     jsonapi: ['application/vnd.api+json']
    # docs_formats:
    #     jsonld: ['application/ld+json']
    #     jsonopenapi: ['application/vnd.openapi+json']
    #     html: ['text/html']
    # defaults:
    #     stateless: true
    #     cache_headers:
    #         vary: ['Content-Type', 'Authorization', 'Origin']
    #     extra_properties:
    #         standard_put: true
    #         rfc_7807_compliant_errors: true
    # event_listeners_backward_compatibility_layer: false
    # keep_legacy_inflector: false
