vich_uploader:
    db_driver: orm

    mappings:
        kbis_upload:
            uri_prefix: /files/kbis
            upload_destination: '%kernel.project_dir%/files/kbis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
