# config/packages/vich_uploader.yaml

vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    media_object:
      uri_prefix: /media
      upload_destination: '%kernel.project_dir%/public/media'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    kbis_upload:
      uri_prefix: /files/kbis
      upload_destination: '%kernel.project_dir%/files/kbis'
      directory_namer: App\Naming\CompanyDirectoryNamer
      namer:
        service: Vich\UploaderBundle\Naming\SmartUniqueNamer
