name: CD

on:
  workflow_dispatch:inputs:
    environment:
      description: "Environnement de déploiement"
      required: true
      default: "production"
      type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to production"
