name: Frontend tests

on:
  workflow_call:

jobs:
  install-front-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/client/package-lock.json') }}
          restore-keys: |
            node_modules-${{ runner.os }}

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Cache dist directory
        uses: actions/cache@v2
        with:
          path: ./client/dist
          key: dist-${{ runner.os }}-${{ hashFiles('**/client/dist/index.html') }}
          restore-keys: |
            dist-${{ runner.os }}

  lint:
    runs-on: ubuntu-latest
    needs: install-front-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use cache node_modules
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/client/package-lock.json') }}

      - name: Lint
        run: npm run lint
        working-directory: ./client
        continue-on-error: true

  test_frontend:
    runs-on: ubuntu-latest
    needs: install-front-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use cache node_modules directory
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/client/package-lock.json') }}

      - name: Run Jest
        run: npm run test
        working-directory: ./client
