name: Frontend tests

on:
  workflow_call:

jobs:
  install-front-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Compress build
        run: tar -czf /tmp/build.tar.gz -C ${{ github.workspace }}/client .

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: /tmp/build.tar.gz

  lint:
    runs-on: ubuntu-latest
    needs: install-front-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build directory
        uses: actions/download-artifact@v3
        with:
          name: build
          path: /tmp

      - name: Uncompress build directory
        run: tar -xzf /tmp/build.tar.gz -C ${{ github.workspace }}/client

      - name: Lint
        run: npm run lint
        working-directory: ./client
        continue-on-error: true

  test_frontend:
    runs-on: ubuntu-latest
    needs: install-front-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build directory
        uses: actions/download-artifact@v3
        with:
          name: build
          path: /tmp

      - name: Uncompress build directory
        run: tar -xzf /tmp/build.tar.gz -C ${{ github.workspace }}/client

      - name: Run Jest
        run: npm run test
        working-directory: ./client
