name: CI

on:
  push:
    branches:
      - dev
      - feature/*
      - fix/*
      - hotfix/*
      - feat/*
jobs:
  backend:
    uses: ./.github/workflows/backend.yml

  frontend:
    uses: ./.github/workflows/frontend.yml


name: Merge Dev to Main

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge dev to main
        run: |
          git checkout main
          git pull origin main
          git merge dev
          git push origin main

name: CD
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to production"
          