name: CI

on:
  push:
    branches:
      - dev
      - feature/*
      - fix/*
      - hotfix/*
      - feat/*
jobs:
  backend:
    uses: ./.github/workflows/backend.yml
    secrets: inherit

  frontend:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
