name: Backend tests

on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        with:
          working-directory: ./server

      - name: Run PHPUnit
        run: php bin/phpunit tests/.
