name: Backend tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2.18"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ./server
      - name: Install Lexik keys
        run: php bin/console lexik:jwt:generate-keypair
        working-directory: ./server

      - name: Run PHPUnit
        run: php bin/phpunit ./server/tests/.
